### ISSUE TITLE
你好，为什么我执行deepl的翻译程序后，没有任何的输出啊

### ISSUE THREAD

**Issue by Aleduohm** [danielqingz/spiders#1]
你好，为什么我执行deepl的翻译程序后，没有任何的输出啊
![image](https://user-images.githubusercontent.com/84367663/195513088-8cae9c5e-9e35-4749-bd05-1e50f0dad571.png)
output.txt 里面什么内容都没有

**Comment by danielqingz** [comment]
你好～请问你运行程序时webdriver成功打开网页了吗？
